#!/bin/bash

# Console entry script for docker container

# Run jupyter notebook
jupyter lab --ip=0.0.0.0 --allow-root --port=8888 \
				--ContentsManager.allow_hidden=True \
				--notebook-dir=/app/notebooks