version: "3.8"
services:
  app:
    image: computervision:latest
    container_name: computervision
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    build: 
      context: .
      network: host
      dockerfile: Dockerfile
      args:
        - DEV_computervision=1
    ipc: host
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - HOME=/app
    - DATA_ROOT=/app/data
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - appdata:/app/data
volumes:
  appdata:
    external: false