services:
  app:
    image: ghcr.io/ccb-hms/computervision:latest
    container_name: computervision
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    ipc: host
    environment:
      - HF_HOME=/app/data
      - TORCH_HOME=/app/data
      - DATA_DIR=/app/data
    env_file:
      - ./.env
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:
      - .:/app
      - ./data:/app/data