version: "3.8"
services:
  app:
    image: computervision:latest
    container_name: computervision
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    build: 
      context: .
      network: host
      dockerfile: Dockerfile
      args:
        - DEV_computervision=1
    ipc: host
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - HOME=/app
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - app_data:/app/data

volumes:
  app_data:
    external: false