[project]
name = "computervision"
version = "0.0.1"
description = "The CCB Computer Vision Repository"
readme = "README.md"
authors = [
    { name = "Andreas Werdich", email = "andreas_werdich@hms.harvard.edu" }
]
requires-python = ">=3.12"
dependencies = [
    "scikit-image>=0.25.2",
    "albumentationsx>=2.0.10",
    "transformers>=4.56.1",
    "tqdm>=4.67.1",
    "jupyterlab>=4.4.7",
    "ipywidgets>=8.1.7",
    "pandas-stubs>=2.3.2.250827",
    "protobuf<5.0",
    "seaborn>=0.13.2",
    "python-dotenv>=1.2.1",
    "opencv-python-headless>=4.13.0.90",
    "pyarrow>=23.0.0",
    "torch>=2.10.0",
    "torchvision>=0.25.0",
    "scikit-learn>=1.8.0",
    "lightning[extra]>=2.6.1",
    "tensorboard>=2.20.0",
    "setuptools<=81",
    "grad-cam>=1.5.5",
    "pytest>=9.0.2",
    "accelerate>=1.14.0",
]

[build-system]
requires = ["setuptools>=41, <81", 
            "wheel", 
            "setuptools-git-versioning>=2.0,<3"]
build-backend = "setuptools.build_meta"

[tool.uv]
python-preference = "system"

[project.scripts]
computervision = "computervision:main"
